theme: "r-hugo-theme"

languages:
  en:
    baseURL: https://rafalkaron.github.io/r-hugo-theme-demo/en/
    languageName: EN
    languageCode: "en-us"
    description: "Site description."
    author: "Name Surname"
    weight: 1
    menu:
      main:
        - Name: "Home"
          URL: "/"
          weight: 1
        - Name: "Section"
          URL: "/section/"
          weight: 2
        - Name: "Blog"
          URL: "/blog/"
          weight: 3
  pl:
    baseURL: https://rafalkaron.github.io/r-hugo-theme-demo/pl/
    languageName: PL
    languageCode: "pl-pl"
    description: "Opis strony."
    author: "Imię Nazwisko"
    weight: 2
    menu:
      main:
        - Name: "Strona główna"
          URL: "/"
          weight: 1
        - Name: "Sekcja"
          URL: "/section/"
          weight: 2
        - Name: "Blog"
          URL: "/blog/"
          weight: 3

Params:
  title: "R"
  favicon_href: "img/favicon.svg"
  # Footer
  email: "mailto:mail@domain.com"
  github: "https://github.com/rafalkaron/r-hugo-theme"
  linkedin: "https://linkedin.com/in/linkedin_id"
  twitter: "https://twitter.com/twitter_id"
  five_o_o_px: "https://500px.com/500px_id"

# Enable related links/see alsos
related:
  indices:
    - name: keywords
      weight: 100
  threshold: 80
  toLower: false

# Markdown rendering settings
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    codeFences: true
    noClasses: true
    style: monokai
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
