baseURL: "https://rafalkaron.github.io/"
languageCode: "en-us"
title: "R."
params: description = "TODO"
theme: "r-hugo-theme"

Menus:
  main:
    - Name: "Portfolio"
      URL: "/"
      weight: 1
    - Name: "Docs"
      URL: "/docs"
      weight: 2
    - Name: "Gallery"
      URL: "/gallery"
      weight: 3
    - Name: "Blog"
      URL: "/blog"
      weight: 4
      layout: "blog"

Params:
  # Leave blank to automatically remove icon from the footer
  email: "mailto:mail@domain.com"
  github: "https://github.com/github_id"
  linkedin: "https://linkedin.com/in/linkedin_id"
  twitter: "https://twitter.com/twitter_id"
  five_o_o_px: "https://500px.com/500px_id"

  # Add favicon
  favicon_href: "img/favicon.svg"
  # Add site logo to the header, leave blank to skip
  logo_href:

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    codeFences: true
    noClasses: true
    style: monokai
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
