baseURL: "https://rafalkaron.github.io/"
languageCode: "en-us"
title: "RK"
params: description = "TODO"
theme: "r-hugo-theme"

Menus:
  main:
    - Name: "Site"
      URL: "/"
      weight: 1
    - Name: "Structure"
      URL: "/structure"
      weight: 2
    - Name: "Blog"
      URL: "/blog"
      weight: 3

Params:
  - email: "mailto:mail@domain.com"
  - github: "https://github.com/github_id"
  - linkedin: "https://linkedin.com/in/linkedin_id"
  - twitter: "https://twitter.com/twitter_id"
  - 500px: "https://500px.com/500px_id"
