baseURL: "https://rafalkaron.github.io/"
languageCode: "en-us"
theme: "r-hugo-theme"

Params:
  title: "R"
  description: "Site description."
  author: "Name Surname"
  favicon_href: "img/favicon.svg"

  # Footer icons
  email: "mailto:mail@domain.com"
  github: "https://github.com/rafalkaron/r-hugo-theme"
  linkedin: "https://linkedin.com/in/linkedin_id"
  twitter: "https://twitter.com/twitter_id"
  five_o_o_px: "https://500px.com/500px_id"

# Languages
defaultContentLanguage: en
languages:
  en:
    title: "R"
    weight: 1
  pl:
    title: "R"
    weight: 2

# See alsos
related:
  indices:
    - name: keywords
      weight: 100
  threshold: 80
  toLower: false

# Navigation
# End each URL with "/" to make active pages work
Menus:
  main:
    - Name: "Home"
      URL: "/"
      weight: 1
    - Name: "Subpages"
      URL: "/subpages/"
      weight: 2
    - Name: "Blog"
      URL: "/blog/"
      weight: 3

#Taxonomies:
#  tag: "tags"

# Rendering settings
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    codeFences: true
    noClasses: true
    style: monokai
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
