baseURL: "https://rafalkaron.github.io/"
languageCode: "en-us"
title: "RK"
params: description = "TODO"
theme: "r-hugo-theme"

Menus:
  main:
    - Name: "Site"
      URL: "/"
      weight: 1
    - Name: "Structure"
      URL: "/structure"
      weight: 2
    - Name: "Blog"
      URL: "/blog"
      weight: 3

Params:
  # Leave blank to automatically remove icon from the footer
  email: "mailto:mail@domain.com"
  github: "https://github.com/github_id"
  linkedin: "https://linkedin.com/in/linkedin_id"
  twitter: "https://twitter.com/twitter_id"
  five_o_o_px: "https://500px.com/500px_id"

  # Add favicon
  favicon_href: "img/favicon.svg"
  # Add site logo to the header, leave blank to skip
  logo_href: "img/logo.svg"
