baseURL: "https://rafalkaron.github.io/"
languageCode: "en-us"
title: "RK"
params: description = "TODO"
theme: "r-hugo-theme"

Menus:
  main:
    - Name: "Site"
      URL: "/site"
      weight: 1
    - Name: "Structure"
      URL: "/structure"
      weight: 2
    - Name: "Blog"
      URL: "/blog"
      weight: 3
