baseURL: "https://rafalkaron.github.io/"
languageCode: "en-us"
title: "RK"
params: description = "TODO"
theme: "r-hugo-theme"

Menus:
  main:
    - Name: "Home"
      URL: "/home"
    - Name: "Blog"
      URL: "/blog"
